### ISSUE TITLE
Segmentation fault while running example 11

### ISSUE THREAD

**Issue by aniket11bh** [esa/pykep#96] opened 2019-05-26 06:01 UTC
Platform information : 
* macOS Mojave, 10.14.4

Got `libsnopt7.dylib` from https://ccom.ucsd.edu/~optimizers/downloads/ 

### Example 11
```python
Python 2.7.15 | packaged by conda-forge | (default, Feb 27 2019, 20:44:16) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykep as pk
>>> pk.examples.run_example11()
```
**Output :** 

```
 ==============================
    SNOPT  C interface  2.2.0   
 ==============================
 S N O P T  7.7.1    (Nov 2018)
 ==============================
 
 SNMEMA EXIT 100 -- finished successfully
 SNMEMA INFO 104 -- memory requirements estimated

 Trial version of SNOPT -- for evaluation or academic purposes only
 

 Nonlinear constraints      37     Linear constraints       1
 Nonlinear variables        93     Linear variables         0
 Jacobian  variables        93     Objective variables     93
 Total constraints          38     Total variables         93
 

 
Segmentation fault: 11
```

### I also tried running following example : 

```python
from pygmo import *
from pygmo_plugins_nonfree import snopt7
from pykep.examples import add_gradient, algo_factory

algo = algorithm(snopt7(screen_output = False, library = "libsnopt7.dylib"))

algo.set_verbosity(1)
prob = problem(cec2006(prob_id = 1))
prob.c_tol = [1e-6]*9
pop = population(prob, 1)
pop = algo.evolve(pop)
print pop
```
**Output :** 

```
SNOPT7 plugin for pagmo/pygmo: 
The gradient sparsity is assumed dense: 130 components detected.
The gradient is computed numerically by SNOPT7.

Insufficient storage allocated - not enough integer storage
Problem name: CEC2006 - g1
	Global dimension:			13
	Integer dimension:			0
	Fitness dimension:			10
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	9
	Tolerances on constraints: [1e-06, 1e-06, 1e-06, 1e-06, 1e-06, ... ]
	Lower bounds: [0, 0, 0, 0, 0, ... ]
	Upper bounds: [1, 1, 1, 1, 1, ... ]

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 1

	Thread safety: basic

Population size: 1

List of individuals: 
#0:
	ID:			5957976106111536803
	Decision vector:	[0.983528, 0.646107, 0.307131, 0.622509, 0.663707, ... ]
	Fitness vector:		[-214.431, -214.431, -214.431, -214.431, -214.431, ... ]

Champion decision vector: [0.983528, 0.646107, 0.307131, 0.622509, 0.663707, ... ]
Champion fitness: [-214.431, -214.431, -214.431, -214.431, -214.431, ... ]
```

**I am not sure why i am facing this problem**.

Thanks,
Aniket

**Comment by darioizzo** [comment] 2019-05-26 12:27
You need to specify the snopt7 minor version you use (that is 7 from the log). Check the documentation of pygmo_plugins_nonfree.
```python
algo = algorithm(snopt7(screen_output = False, library = "libsnopt7.dylib", minor_version=7))
```

**Comment by aniket11bh** [comment] 2019-05-26 17:32
Yeah I checked the documentation 
```python
class snopt7(Boost.Python.instance)
 |  __init__(screen_output = False, library = "/usr/local/lib/libsnopt7.so", minor_version=6)
 |  
 |  SNOPT 7 - (Sparse Nonlinear OPTimizer, Version 7)
 |  
 |  This class is a user-defined algorithm (UDA) that contains a plugin to the Sparse Nonlinear OPTimizer (SNOPT, V7)
 |  solver, a software package for large-scale nonlinear optimization. SNOPT7 is a powerful solver that is able to handle
 |  robustly and efficiently constrained nonlinear opimization problems also at high dimensionalities.
 |  
 |  Intended use::
 |     >>> import pygmo as pg
 |     >>> import pygmo_plugins_nonfree as ppnf
 |     >>> uda = ppnf.snopt7(screen_output = False, library = "/usr/local/lib/libsnopt76.so", minor_version = 6)
 |     >>> algo = pg.algorithm(uda)
 |  
 |  SNOPT7 supports only single-objective minimisation, using a sequential quadratic programming (SQP) algorithm.
 |  Search directions are obtained from QP subproblems that minimize a quadratic model of the Lagrangian function
 |  subject to linearized constraints. An augmented Lagrangian merit function is reduced along each search
 |  direction to ensure convergence from any starting point.

```
**But I'm still getting same issue**
```
SNOPT7 plugin for pagmo/pygmo: 
The gradient sparsity is assumed dense: 130 components detected.
The gradient is computed numerically by SNOPT7.

Insufficient storage allocated - not enough integer storage
Problem name: CEC2006 - g1
        Global dimension:                       13
        Integer dimension:                      0
        Fitness dimension:                      10
        Number of objectives:                   1
        Equality constraints dimension:         0
        Inequality constraints dimension:       9
        Tolerances on constraints: [1e-06, 1e-06, 1e-06, 1e-06, 1e-06, ... ]
        Lower bounds: [0, 0, 0, 0, 0, ... ]
        Upper bounds: [1, 1, 1, 1, 1, ... ]

        Has gradient: false
        User implemented gradient sparsity: false
        Has hessians: false
        User implemented hessians sparsity: false

        Fitness evaluations: 1

        Thread safety: basic

Population size: 1

List of individuals: 
#0:
        ID:                     16178374945473041796
        Decision vector:        [0.340552, 0.040306, 0.967221, 0.877577, 0.904689, ... ]
        Fitness vector:         [-169.673, -169.673, -169.673, -169.673, -169.673, ... ]

Champion decision vector: [0.340552, 0.040306, 0.967221, 0.877577, 0.904689, ... ]
Champion fitness: [-169.673, -169.673, -169.673, -169.673, -169.673, ... ]
```

**Comment by darioizzo** [comment] 2019-05-27 06:26
Cannot reproduce. Your code runs in our system (linux / wndows, snopt 7.2 / 7.7 (student edition)).

It looks like an issue on your snopt C library? (Insufficient storage allocated - not enough integer storage
)

How did you obtain the library?

**Comment by aniket11bh** [comment] 2019-05-27 06:31
I registered myself to get the library from : https://ccom.ucsd.edu/~optimizers/downloads/.

Then i got a mail from them. 

And from the list below, I downloaded `Fortran/C Libraries MacOS (gfortran)` marked green below.

![image](https://user-images.githubusercontent.com/8214876/58399719-b86a9600-8076-11e9-9067-31fc70cab36b.png)

**Comment by aniket11bh** [comment] 2019-05-27 06:35
Also, to mention the above library had dependencies on `libgfortran-4` and other similar dependencies. So i had to install `gcc48` rather than the latest one to get the correct library dependencies.

**Comment by darioizzo** [comment] 2019-05-27 06:49
```
Insufficient storage allocated - not enough integer storage
```
This is your problem. Its the SnJac routine that complains ... probably some weird interactions between the libraries and OSX .... not sure .... cannot really help as I cannot reproduce the issue locally.

**Comment by aniket11bh** [comment] 2019-05-27 07:50
oh okay. I will try on windows/linux then to ensure.

**Comment by darioizzo** [comment] 2019-11-30 08:07
closing this as its an issue with pygmo plugins nonfree rather than pykep. Feel free to open a separate issue there.

**Closed by darioizzo** 2019-11-30 08:07 UTC
