### ISSUE TITLE
Attempting to install PyKep under Python 3.6

### ISSUE THREAD

**Issue by OrbitalMechanic** [esa/pykep#74] opened 2018-04-06 04:27 UTC
I'm attempting to install PyKep on a Mac Pro (desktop) running Anaconda distribution for Python 3.6. The operating system is Mac OS X v. 10.12.6 (Sierra).

The problem I'm presently having is with specifying the directory containing the CMake configuration file for Boost. In looking through the Boost directory installed for the Anaconda Python 3, no CMake configuration file was found. I also have a version of Boost installed via Homebrew.

Beginning with my present problem, when Boost is installed for Anaconda, where does the CMake configuration reside? Now if I need to reinstall Boost, what is the procedure I need to follow?

Looking forward to hearing from you.

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-06 06:47
Can you just ```conda install pykep```?

**Comment by OrbitalMechanic** [comment] 2018-04-07 03:00
Dario Izzo,

Thank you for responding to my note. I followed your suggestion and PyKep installed successfully. When I attempted to run the example cited on http://esa.github.io/pykep/examples/ex1.html, I get the following response:

Samuels-Mac-Pro:~ user$ python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykep as pk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pykep/__init__.py", line 48, in <module>
    from pykep import core, sims_flanagan, pontryagin, orbit_plots, examples, phasing, util, planet, trajopt
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pykep/pontryagin/__init__.py", line 4, in <module>
    from ._leg import leg
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pykep/pontryagin/_leg.py", line 1, in <module>
    from pykep.pontryagin._dynamics import _dynamics
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pykep/pontryagin/_dynamics.py", line 6, in <module>
    class _dynamics(object):
  File "/Users/user/anaconda3/lib/python3.6/site-packages/pykep/pontryagin/_dynamics.py", line 8, in _dynamics
    def __init__(self, sc=spacecraft(1000, 0.3, 2500), mu=MU_SUN, alpha=1, bound=True):
TypeError: __init__() should return None, not 'NoneType'
>>>

Is there something I'm missing? Are there any prerequisites to PyKep I need to install?

Please advise.

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-07 07:09
Sam,

can you try from a fresh and new conda environment? 

Dario

**Comment by OrbitalMechanic** [comment] 2018-04-07 07:56
Dario,

At present I have a system back-up running. Once I verify that my 
present Anaconda3 environment has been successfully backed-up, I'll 
uninstall it and install a clean new Anaconda3 environment. I'll contact 
with you once I've run PyKep in a cleanly installed Anaconda3 environment.

In the meantime, are there any prerequisites for PyKep that I will need 
to install?

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-07 08:08
conda should install all the needed deps. You should not worry about that.

once you have created a new conda environment
```
conda create -n pagmo python=3.6
```
activate it
```
source activate pagmo
```
and install
```
conda install pykep
```

Then you can install whatever is that you need, numpy, matplolib, etc...

**Comment by OrbitalMechanic** [comment] 2018-04-07 23:04
Dario,

I created a new Anaconda3 environment and followed the procedure you 
cited in your previous note. I'm still having issues with PyKep. After 
doing the install, I ran the example posted on 
https://esa.github.io/pykep/examples/ex1.html with the following results:


(pagmo) Samuels-Mac-Pro:~ user$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pykep as pk
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/__init__.py", 
line 48, in <module>
     from pykep import core, sims_flanagan, pontryagin, orbit_plots, 
examples, phasing, util, planet, trajopt
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/pontryagin/__init__.py", 
line 4, in <module>
     from ._leg import leg
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/pontryagin/_leg.py", 
line 6, in <module>
     import matplotlib.pyplot as plt
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/pyplot.py", 
line 31, in <module>
     import matplotlib.colorbar
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/colorbar.py", 
line 36, in <module>
     import matplotlib.contour as contour
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/contour.py", 
line 20, in <module>
     import matplotlib.font_manager as font_manager
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/font_manager.py", 
line 55, in <module>
     from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: 
dlopen(/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 
2): Symbol not found: _inflateValidate
   Referenced from: /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib
   Expected in: /usr/lib/libz.1.dylib
  in /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib


Any suggestions?

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-08 09:27
Cannot reproduce. On my system here what happens:

```
Darios MacBook Pro:~ darioizzo$ conda create -n prova python=3.6
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/darioizzo/miniconda3/envs/prova:

The following NEW packages will be INSTALLED:

    ca-certificates: 2018.1.18-0      conda-forge
    certifi:         2018.1.18-py36_0 conda-forge
    ncurses:         5.9-10           conda-forge
    openssl:         1.0.2n-0         conda-forge
    pip:             9.0.3-py36_0     conda-forge
    python:          3.6.5-1          conda-forge
    readline:        7.0-0            conda-forge
    setuptools:      39.0.1-py36_0    conda-forge
    sqlite:          3.20.1-2         conda-forge
    tk:              8.6.7-0          conda-forge
    wheel:           0.31.0-py36_0    conda-forge
    xz:              5.2.3-0          conda-forge
    zlib:            1.2.11-0         conda-forge

Proceed ([y]/n)? y

python-3.6.5-1 100% |##########################################################################################| Time: 0:00:11   1.26 MB/s
setuptools-39. 100% |##########################################################################################| Time: 0:00:00   1.28 MB/s
wheel-0.31.0-p 100% |##########################################################################################| Time: 0:00:00  98.88 kB/s
pip-9.0.3-py36 100% |##########################################################################################| Time: 0:00:01 984.76 kB/s
#
# To activate this environment, use:
# > source activate prova
#
# To deactivate an active environment, use:
# > source deactivate
#

(pagmo) Darios MacBook Pro:~ darioizzo$ source activate prova
(prova) Darios MacBook Pro:~ darioizzo$ conda install pykep
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/darioizzo/miniconda3/envs/prova:

The following NEW packages will be INSTALLED:

    boost:        1.66.0-py36_1         conda-forge
    boost-cpp:    1.66.0-1              conda-forge
    bzip2:        1.0.6-1               conda-forge
    icu:          58.2-0                conda-forge
    intel-openmp: 2018.0.0-8                       
    libgfortran:  3.0.1-h93005f0_2                 
    mkl:          2018.0.2-1                       
    mkl_fft:      1.0.1-py36_1          conda-forge
    mkl_random:   1.0.1-py36_0          conda-forge
    numpy:        1.14.2-py36ha9ae307_1            
    pykep:        2.1-py36_1            conda-forge

Proceed ([y]/n)? y

intel-openmp-2 100% |##########################################################################################| Time: 0:00:00   2.67 MB/s
libgfortran-3. 100% |##########################################################################################| Time: 0:00:00   3.02 MB/s
mkl-2018.0.2-1 100% |##########################################################################################| Time: 0:01:03   2.41 MB/s
pykep-2.1-py36 100% |##########################################################################################| Time: 0:00:02   1.11 MB/s
mkl_fft-1.0.1- 100% |##########################################################################################| Time: 0:00:01  98.41 kB/s
mkl_random-1.0 100% |##########################################################################################| Time: 0:00:01 337.11 kB/s
numpy-1.14.2-p 100% |##########################################################################################| Time: 0:00:01   2.38 MB/s
(prova) Darios MacBook Pro:~ darioizzo$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykep as pk
```

So the issue is related to something weird going on thre user your system.

**Comment by bluescarni** [comment] 2018-04-08 13:09
The key portion of the error here seems to be the following:

```
ImportError: dlopen(/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 2): Symbol not found: _inflateValidate   Referenced from: /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib   Expected in: /usr/lib/libz.1.dylib  in /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib
```

This has nothing to do with pykep per se. It is complaining that, while loading a component of matplotlib, the linker is not finding a symbol named ``_inflateValidate`` in the library  ``/usr/lib/libz.1.dylib``. I don't use OSX myself so I cannot tell with certainty, but it seems strange to me that here matplotlib is attempting to load the ``libz`` library from the system rather than the one provided with anaconda. My guess would be that you have some misconfiguration of system libraries or library paths on your end.

**Comment by OrbitalMechanic** [comment] 2018-04-09 04:24
Can you give me some idea of what the library path should be ideally, or 
what I should look for in terms of a misconfiguration of system libraries?

Sam Dupree.

**Comment by OrbitalMechanic** [comment] 2018-04-09 04:33
I noticed you're using miniconda and installing selected packages as 
opposed to anaconda with its default set of packages. If I may ask, what 
version of matplotlib are you running? Second, can you give me some idea 
of what the library path should be ideally, or what I should look for in 
terms of a misconfiguration of system libraries?

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-09 07:42
As you can see from the installation above, no matplotlib is required for pykep installation.
If you do have matplotlib, then pykep will try to import it. If that fails the problem may be related to your matplotlib?
Can you import matplotlib at all in your system?

**Comment by OrbitalMechanic** [comment] 2018-04-10 05:49
I removed matplotlib from my pagmo environment and the command

    import  pykep  as  pk

works. Now when I attempt to execute the entire example,

import  pykep  as  pkpk.examples.run_example1(impulses  =  3)

the response I get is

(pagmo) Samuels-Mac-Pro:pykep user$ python
Python 3.6.0 | packaged by conda-forge | (default, Feb 10 2017, 07:08:35)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pykep as pk
 >>> pk.examples.run_example1(impulses = 3)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
AttributeError: module 'pykep.examples' has no attribute 'run_example1'

What is going on here?

Before I uninstalled matplotlib, I was able to import matplotlib with no 
problems. In reviewing the response I get with matplotlib installed, the 
response I get is

Samuels-Mac-Pro:~ user$ source activate pagmo
(pagmo) Samuels-Mac-Pro:~ user$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
 >>> import pykep as pk
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/__init__.py", 
line 48, in <module>
     from pykep import core, sims_flanagan, pontryagin, orbit_plots, 
examples, phasing, util, planet, trajopt
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/pontryagin/__init__.py", 
line 4, in <module>
     from ._leg import leg
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/pykep/pontryagin/_leg.py", 
line 6, in <module>
     import matplotlib.pyplot as plt
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/pyplot.py", 
line 31, in <module>
     import matplotlib.colorbar
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/colorbar.py", 
line 36, in <module>
     import matplotlib.contour as contour
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/contour.py", 
line 20, in <module>
     import matplotlib.font_manager as font_manager
   File 
"/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/font_manager.py", 
line 55, in <module>
     from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: 
dlopen(/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 
2): Symbol not found: _inflateValidate
   Referenced from: /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib
   Expected in: /usr/lib/libz.1.dylib
  in /Users/user/anaconda3/envs/pagmo/lib/libpng16.16.dylib
 >>>

I believe the issue here is that problem is with matplotlib in the 
generation of the file,

/Users/user/anaconda3/envs/pagmo/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so

I don't know how to fixing or working around this issue with matplotlib 
and how ft2font.cpython-36m-darwin.so is generated.


Any suggestions or advice?

Sam Dupree.

**Comment by darioizzo** [comment] 2018-04-10 05:56
Sam,

when you import pykep, it detects what optional dependencies you have installed (see the docs https://esa.github.io/pykep/documentation/index.html).

According to the installed deps, it will import some examples and some will be neglected. In your case, since matplotlib is your problem, pykep simply does not import the examples using it (most of the I guess).

Cannot really help with your issue (realted to matplotlib). 

Will close this.

**Closed by darioizzo** 2018-04-10 05:56 UTC
